export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAIL = 'CREATE_USER_FAIL';

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';

export const ADD_LIST = 'ADD_LIST';
export const FETCH_ALL_LISTS = 'FETCH_ALL_LISTS';
export const CHANGE_LIST_TITLE = 'CHANGE_LIST_TITLE';
export const DELETE_LIST = 'DELETE_LIST';
